CREATE TABLE support_tickets (
                                 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                                 created_by_user_id BIGINT NOT NULL,
                                 title VARCHAR(300) NOT NULL,
                                 description TEXT NOT NULL,

                                 category VARCHAR(60) NOT NULL,
                                 priority VARCHAR(20) NOT NULL,
                                 status VARCHAR(30) NOT NULL,

                                 page_url TEXT,
                                 user_agent TEXT,

                                 github_issue_number INTEGER,
                                 github_issue_url TEXT,
                                 github_issue_state VARCHAR(20),

                                 created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
                                 updated_at TIMESTAMPTZ
);

ALTER TABLE support_tickets
    ADD CONSTRAINT fk_support_tickets_created_by
        FOREIGN KEY (created_by_user_id) REFERENCES users(id);

CREATE UNIQUE INDEX uq_support_tickets_github_issue_number
    ON support_tickets (github_issue_number)
    WHERE github_issue_number IS NOT NULL;

CREATE INDEX idx_support_tickets_created_by_user
    ON support_tickets (created_by_user_id);

CREATE INDEX idx_support_tickets_status
    ON support_tickets (status);