-- Global Anlass-Katalog (system-wide, not per Träger)
CREATE TABLE IF NOT EXISTS anlass_catalog (
    id               BIGSERIAL PRIMARY KEY,
    code             VARCHAR(120) NOT NULL,
    label            VARCHAR(300) NOT NULL,
    category         VARCHAR(150),
    default_severity SMALLINT,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uk_anlass_catalog_code UNIQUE (code)
);

CREATE INDEX IF NOT EXISTS ix_anlass_catalog_code ON anlass_catalog(code);
CREATE INDEX IF NOT EXISTS ix_anlass_catalog_label ON anlass_catalog USING gin (to_tsvector('german', label));

INSERT INTO anlass_catalog (code, label, category, default_severity) VALUES
-- Körperbezogene Anlässe
('BODY_INJURY_VISIBLE','Sichtbare Verletzungen','Körperbezogene Anlässe',2),
('BODY_INJURY_REPEATED','Wiederholte Verletzungen','Körperbezogene Anlässe',3),
('BODY_INJURY_EXPLANATION_ODD','Unplausible Erklärung für Verletzungen','Körperbezogene Anlässe',2),
('BODY_PUNISHMENT_HINT','Hinweis auf körperliche Bestrafung','Körperbezogene Anlässe',2),
('BODY_BURNS_OR_SCALDS','Verbrennungen oder Verbrühungen','Körperbezogene Anlässe',3),
('BODY_BRUISES_PATTERNED','Auffällige Hämatome / Verletzungsmuster','Körperbezogene Anlässe',3),
('BODY_FRACTURE_SUSPICION','Verdacht auf Frakturen / schwere körperliche Misshandlung','Körperbezogene Anlässe',3),
('BODY_MALNUTRITION','Mangelernährung','Körperbezogene Anlässe',2),
('BODY_DEHYDRATION','Hinweise auf Dehydrierung','Körperbezogene Anlässe',3),
('BODY_MEDICAL_NEGLECT','Medizinische Vernachlässigung','Körperbezogene Anlässe',2),
('BODY_NEGLECT_APPEARANCE','Vernachlässigtes Erscheinungsbild','Körperbezogene Anlässe',1),
('BODY_POOR_HYGIENE','Auffällige mangelnde Hygiene','Körperbezogene Anlässe',1),
('BODY_INADEQUATE_CLOTHING','Unangemessene / fehlende Kleidung','Körperbezogene Anlässe',1),
('BODY_PSYCHOSOMATIC','Psychosomatische Beschwerden','Körperbezogene Anlässe',1),
('BODY_SELF_HARM','Selbstverletzendes Verhalten','Körperbezogene Anlässe',3),
('BODY_ACUTE_HEALTH','Akute gesundheitliche Gefährdung','Körperbezogene Anlässe',3),
-- Psychische / emotionale Anlässe
('PSYCH_EXTREME_FEAR','Ausgeprägte Angst / Furchtsamkeit','Psychische / emotionale Anlässe',2),
('PSYCH_WITHDRAWAL','Starker Rückzug / sozialer Rückzug','Psychische / emotionale Anlässe',1),
('PSYCH_DEPRESSION_SIGNS','Hinweise auf depressive Symptomatik','Psychische / emotionale Anlässe',2),
('PSYCH_TRAUMA_SIGNS','Trauma-Anzeichen / starke Übererregung','Psychische / emotionale Anlässe',2),
('PSYCH_SLEEP_DISTURBANCE','Massive Schlafstörungen / Albträume','Psychische / emotionale Anlässe',1),
('PSYCH_REGRESSION','Deutliche Regression im Verhalten','Psychische / emotionale Anlässe',1),
('PSYCH_AGGRESSIVE_BEHAVIOR','Auffällige Aggressivität','Psychische / emotionale Anlässe',1),
('PSYCH_APATHY','Apathie / emotionale Abflachung','Psychische / emotionale Anlässe',2),
('PSYCH_LOW_SELF_WORTH','Stark vermindertes Selbstwertgefühl','Psychische / emotionale Anlässe',1),
('PSYCH_PARENTIFICATION','Übermäßige Verantwortungsübernahme / Parentifizierung','Psychische / emotionale Anlässe',2),
('PSYCH_SUICIDAL_HINT','Suizidale Äußerungen / Hinweise','Psychische / emotionale Anlässe',3),
('PSYCH_EMOTIONAL_ABUSE_HINT','Hinweise auf seelische Misshandlung','Psychische / emotionale Anlässe',2),
-- Sexualisierte Gewalt
('SEXUAL_DISCLOSURE','Äußerung über sexuelle Übergriffe','Sexualisierte Gewalt / Grenzverletzungen',3),
('SEXUAL_BEHAVIOR_INAPPROPRIATE','Altersunangemessen sexualisiertes Verhalten','Sexualisierte Gewalt / Grenzverletzungen',3),
('SEXUAL_BOUNDARY_VIOLATION','Hinweise auf sexuelle Grenzverletzungen','Sexualisierte Gewalt / Grenzverletzungen',3),
('SEXUAL_GENITAL_INJURY','Verletzungen / Beschwerden im Intimbereich','Sexualisierte Gewalt / Grenzverletzungen',3),
('SEXUAL_STI_PREGNANCY','Sexuell übertragbare Infektion / Schwangerschaft mit Verdachtsmoment','Sexualisierte Gewalt / Grenzverletzungen',3),
('SEXUAL_EXPOSURE_TO_PORN','Konfrontation mit Pornografie / sexualisierten Inhalten','Sexualisierte Gewalt / Grenzverletzungen',2),
('SEXUAL_GROOMING_HINT','Hinweise auf Grooming','Sexualisierte Gewalt / Grenzverletzungen',3),
('SEXUAL_ONLINE_EXPLOITATION','Hinweise auf digitale sexuelle Ausbeutung','Sexualisierte Gewalt / Grenzverletzungen',3),
('SEXUAL_PROSTITUTION_EXPLOITATION','Hinweise auf sexuelle Ausbeutung','Sexualisierte Gewalt / Grenzverletzungen',3),
-- Vernachlässigung
('NEGLECT_FOOD','Unzureichende Ernährung','Vernachlässigung',2),
('NEGLECT_HYGIENE','Unzureichende Hygieneversorgung','Vernachlässigung',1),
('NEGLECT_CLOTHING','Unzureichende Bekleidung','Vernachlässigung',1),
('NEGLECT_SLEEP_PLACE','Ungeeigneter Schlafplatz / fehlender Schlafplatz','Vernachlässigung',2),
('NEGLECT_MEDICAL_CARE','Nicht sichergestellte medizinische Versorgung','Vernachlässigung',2),
('NEGLECT_SUPERVISION_BASIC','Grundlegende Versorgung nicht sichergestellt','Vernachlässigung',2),
('NEGLECT_EDUCATION','Schulische / institutionelle Vernachlässigung','Vernachlässigung',1),
('NEGLECT_EMOTIONAL','Emotionale Vernachlässigung','Vernachlässigung',2),
('NEGLECT_CHRONIC','Chronische Vernachlässigung','Vernachlässigung',3),
('NEGLECT_INFANT_CARE','Unzureichende Säuglings- / Kleinkindversorgung','Vernachlässigung',3),
-- Aufsicht
('SUPERVISION_LEFT_ALONE','Kind wiederholt unbeaufsichtigt','Aufsicht / Schutz / Gefahrenexposition',2),
('SUPERVISION_AGE_INAPPROPRIATE','Aufsicht entspricht nicht dem Alter / Entwicklungsstand','Aufsicht / Schutz / Gefahrenexposition',2),
('SUPERVISION_DANGEROUS_ENVIRONMENT','Gefährliche Umgebung frei zugänglich','Aufsicht / Schutz / Gefahrenexposition',2),
('SUPERVISION_TRAFFIC_RISK','Erhöhte Verkehrs- / Wegesicherheitsgefährdung','Aufsicht / Schutz / Gefahrenexposition',2),
('SUPERVISION_SUBSTANCE_ACCESS','Zugang zu Alkohol, Drogen, Medikamenten oder Waffen','Aufsicht / Schutz / Gefahrenexposition',3),
('SUPERVISION_RUNAWAY','Weglaufen / Vermisstensituationen','Aufsicht / Schutz / Gefahrenexposition',2),
('SUPERVISION_NIGHT_UNATTENDED','Nächtliches Alleinlassen','Aufsicht / Schutz / Gefahrenexposition',3),
-- Entwicklung
('DEV_DELAY_NOTICEABLE','Auffällige Entwicklungsverzögerung','Entwicklung / Förderung / Teilhabe',1),
('DEV_LANGUAGE_DELAY','Auffällige Sprachentwicklungsverzögerung','Entwicklung / Förderung / Teilhabe',1),
('DEV_NO_SUPPORT','Fehlende Entwicklungsförderung','Entwicklung / Förderung / Teilhabe',1),
('DEV_SPECIAL_NEEDS_IGNORED','Besonderer Förder- / Unterstützungsbedarf bleibt unbeachtet','Entwicklung / Förderung / Teilhabe',2),
('DEV_SCHOOL_ABSENCE','Auffällige Schulabwesenheit','Entwicklung / Förderung / Teilhabe',2),
('DEV_DAYCARE_ABSENCE','Auffällige Kita-Abwesenheit','Entwicklung / Förderung / Teilhabe',1),
('DEV_SOCIAL_ISOLATION','Soziale Isolation des Kindes','Entwicklung / Förderung / Teilhabe',1),
('DEV_OVERBURDENED_CHILD','Deutliche Überforderung des Kindes','Entwicklung / Förderung / Teilhabe',2),
-- Äußerungen des Kindes
('CHILD_DISCLOSES_VIOLENCE','Kind berichtet von Gewalt','Äußerungen / Signale des Kindes oder Jugendlichen',3),
('CHILD_DISCLOSES_NEGLECT','Kind berichtet von Vernachlässigung','Äußerungen / Signale des Kindes oder Jugendlichen',3),
('CHILD_DISCLOSES_SEXUAL','Kind berichtet von sexualisierter Gewalt','Äußerungen / Signale des Kindes oder Jugendlichen',3),
('CHILD_EXPRESSES_FEAR_OF_HOME','Kind äußert Angst vor Zuhause / Bezugsperson','Äußerungen / Signale des Kindes oder Jugendlichen',3),
('CHILD_DOES_NOT_WANT_HOME','Kind will nicht nach Hause zurück','Äußerungen / Signale des Kindes oder Jugendlichen',2),
('CHILD_REQUESTS_HELP','Kind bittet ausdrücklich um Hilfe / Schutz','Äußerungen / Signale des Kindes oder Jugendlichen',3),
('CHILD_INCONSISTENT_DISTRESS','Starke Belastung ohne altersangemessene Erklärung','Äußerungen / Signale des Kindes oder Jugendlichen',2),
-- Elterliches Verhalten
('PARENT_REJECTING','Stark ablehnendes Verhalten gegenüber dem Kind','Elterliches Verhalten / Erziehungssituation',2),
('PARENT_HUMILIATING','Demütigung / Herabsetzung des Kindes','Elterliches Verhalten / Erziehungssituation',2),
('PARENT_THREATENING','Drohungen gegenüber dem Kind','Elterliches Verhalten / Erziehungssituation',3),
('PARENT_OVERWHELMED','Deutliche Überforderung der Sorgeberechtigten','Elterliches Verhalten / Erziehungssituation',1),
('PARENT_UNCOOPERATIVE','Massive Kooperationsverweigerung im Schutzkontext','Elterliches Verhalten / Erziehungssituation',2),
('PARENT_INCONSISTENT_CARE','Sprunghaftes / unzuverlässiges Fürsorgeverhalten','Elterliches Verhalten / Erziehungssituation',1),
('PARENT_SUBSTANCE_IMPAIRED_CARE','Eingeschränkte Erziehungsfähigkeit durch Suchtmittelkonsum','Elterliches Verhalten / Erziehungssituation',2),
('PARENT_PSYCH_IMPAIRED_CARE','Eingeschränkte Erziehungsfähigkeit aufgrund psychischer Belastung','Elterliches Verhalten / Erziehungssituation',2),
('PARENT_DELUSIONAL_OR_CONFUSED','Schwere psychische Desorganisation mit Auswirkung auf Versorgung','Elterliches Verhalten / Erziehungssituation',3),
('PARENT_FAILURE_TO_PROTECT','Kind wird nicht vor bekannten Gefahren geschützt','Elterliches Verhalten / Erziehungssituation',3),
-- Familiäre Belastung
('FAMILY_DOMESTIC_VIOLENCE','Häusliche Gewalt / Partnerschaftsgewalt','Familiäre Belastung / Familiensystem',3),
('FAMILY_ESCALATING_CONFLICT','Massiv eskalierende familiäre Konflikte','Familiäre Belastung / Familiensystem',2),
('FAMILY_SEPARATION_CRISIS','Trennungs- / Umgangskonflikt mit Kindesbelastung','Familiäre Belastung / Familiensystem',1),
('FAMILY_SUBSTANCE_ABUSE','Suchtbelastung im Familiensystem','Familiäre Belastung / Familiensystem',2),
('FAMILY_MENTAL_ILLNESS','Psychische Erkrankung im Familiensystem','Familiäre Belastung / Familiensystem',2),
('FAMILY_CRIMINAL_CONTEXT','Delinquenz- / Gewaltkontext im nahen Umfeld','Familiäre Belastung / Familiensystem',2),
('FAMILY_CHRONIC_OVERLOAD','Chronische familiäre Überlastung','Familiäre Belastung / Familiensystem',1),
('FAMILY_NO_SUPPORT_NETWORK','Fehlendes unterstützendes Netzwerk','Familiäre Belastung / Familiensystem',1),
('FAMILY_PREVIOUS_PROTECTION_CASE','Frühere Kinderschutzfälle / Vorbefassung','Familiäre Belastung / Familiensystem',2),
-- Wohnsituation
('LIVING_UNSAFE_HOME','Unsichere / gesundheitsgefährdende Wohnsituation','Wohnsituation / materielles Umfeld',2),
('LIVING_FILTH','Massive Vermüllung / Verwahrlosung der Wohnung','Wohnsituation / materielles Umfeld',2),
('LIVING_NO_HEATING_OR_POWER','Fehlende Heizung / Strom / Wasser','Wohnsituation / materielles Umfeld',3),
('LIVING_HOMELESSNESS','Wohnungslosigkeit / drohende Obdachlosigkeit','Wohnsituation / materielles Umfeld',3),
('LIVING_CROWDING','Extreme räumliche Enge / Überbelegung','Wohnsituation / materielles Umfeld',1),
('LIVING_NO_CHILD_SPACE','Kein kindgerechter Rückzugs- oder Lebensraum','Wohnsituation / materielles Umfeld',1),
('LIVING_HAZARDOUS_OBJECTS','Gefährliche Gegenstände / Zustände in der Wohnung','Wohnsituation / materielles Umfeld',2),
-- Soziales Umfeld
('SOCIAL_VIOLENT_PERSON_IN_HOME','Gewaltbereite Person im nahen Umfeld','Soziales Umfeld / Drittgefährdung',3),
('SOCIAL_SEXUAL_RISK_PERSON','Sexuell grenzverletzende / übergriffige Person im Umfeld','Soziales Umfeld / Drittgefährdung',3),
('SOCIAL_PEER_VIOLENCE','Schwere Gewalt im Peer-Kontext','Soziales Umfeld / Drittgefährdung',2),
('SOCIAL_BULLYING_EXTREME','Massives Mobbing mit Gefährdungscharakter','Soziales Umfeld / Drittgefährdung',2),
('SOCIAL_CRIMINAL_EXPLOITATION','Hinweise auf kriminelle Ausbeutung','Soziales Umfeld / Drittgefährdung',3),
('SOCIAL_TRAFFICKING_HINT','Hinweise auf Menschenhandel / Ausbeutung','Soziales Umfeld / Drittgefährdung',3),
-- Digital
('DIGITAL_SEXTORTION_HINT','Hinweise auf Sextortion','Digitale / mediale Gefährdungslagen',3),
('DIGITAL_CYBERGROOMING_HINT','Hinweise auf Cybergrooming','Digitale / mediale Gefährdungslagen',3),
('DIGITAL_IMAGE_SHARING','Verbreitung intimer Aufnahmen','Digitale / mediale Gefährdungslagen',3),
('DIGITAL_ONLINE_CONTROL','Digitale Kontrolle / Überwachung des Kindes','Digitale / mediale Gefährdungslagen',2),
('DIGITAL_HARMFUL_CONTACTS','Gefährdende Online-Kontakte','Digitale / mediale Gefährdungslagen',2),
-- Akute Schutzanlässe
('ACUTE_IMMEDIATE_DANGER','Unmittelbare akute Gefährdung','Akute Schutzanlässe',3),
('ACUTE_CHILD_ABANDONED','Kind wurde zurückgelassen / nicht abgeholt','Akute Schutzanlässe',3),
('ACUTE_CAREGIVER_UNREACHABLE','Sorgeberechtigte nicht erreichbar bei Schutzbedarf','Akute Schutzanlässe',2),
('ACUTE_INTOXICATED_CAREGIVER','Akut intoxikierte Betreuungsperson','Akute Schutzanlässe',3),
('ACUTE_PSYCHIATRIC_CRISIS_CAREGIVER','Akute psychische Krise der Betreuungsperson','Akute Schutzanlässe',3),
('ACUTE_VIOLENCE_ESCALATION','Akute Eskalation von Gewalt','Akute Schutzanlässe',3),
('ACUTE_CHILD_UNDER_THREE_HIGH_RISK','Besonders hohes Risiko bei sehr jungem Kind','Akute Schutzanlässe',3),
-- Sonstiges
('OTHER','Sonstiges','Sonstiges',0)
ON CONFLICT (code) DO NOTHING;
