-- V1__schema.sql
-- Full schema (Non-KWS + KWS) + Facilities + Teams (NO groups)

CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- =========================
-- Orga: Facilities + Teams
-- =========================

CREATE TABLE IF NOT EXISTS public.facilities (
                                                 id BIGSERIAL PRIMARY KEY,
                                                 name TEXT NOT NULL UNIQUE,
                                                 created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.teams (
                                            id BIGSERIAL PRIMARY KEY,
                                            name VARCHAR(255) NOT NULL,
                                            facility_id BIGINT NOT NULL,
                                            created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
                                            CONSTRAINT fk_teams_facility FOREIGN KEY (facility_id) REFERENCES public.facilities(id) ON DELETE CASCADE,
                                            CONSTRAINT uk_team_facility_name UNIQUE (facility_id, name)
);

-- =========================
-- Non-KWS: Personen / Users / Kinder / Fälle / etc.
-- =========================

CREATE TABLE IF NOT EXISTS public.bezugspersonen (
                                                     staatsangehoerigkeit_iso2 varchar(2),
                                                     id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                                     bevorzugte_sprache_code varchar(15),
                                                     dolmetsch_sprache_code varchar(15),
                                                     muttersprache_code varchar(15),
                                                     gebaerdensprache_code varchar(20),
                                                     aufenthaltstitel_details varchar(200),
                                                     kommunikations_hinweise varchar(500),
                                                     aufenthaltstitel_typ varchar(255),
                                                     coda_status varchar(255) NOT NULL,
                                                     dolmetsch_bedarf varchar(255) NOT NULL,
                                                     hausnummer varchar(255),
                                                     hoer_status varchar(255) NOT NULL,
                                                     kontakt_email varchar(255),
                                                     nachname varchar(255),
                                                     organisation varchar(255),
                                                     ort varchar(255),
                                                     plz varchar(255),
                                                     staatsangehoerigkeit_gruppe varchar(255) NOT NULL,
                                                     staatsangehoerigkeit_sonderfall varchar(255) NOT NULL,
                                                     strasse varchar(255),
                                                     telefon varchar(255),
                                                     vorname varchar(255),

                                                     CONSTRAINT bezugspersonen_aufenthaltstitel_typ_check CHECK (aufenthaltstitel_typ::text = ANY (ARRAY[
                                                         'DEUTSCH','EU_EWR_FREIZUEGIGKEIT','SCHWEIZ_FREIZUEGIGKEIT','AUFENTHALTSERLAUBNIS','NIEDERLASSUNGSERLAUBNIS',
                                                         'DAUERAUFENTHALT_EU','BLAUE_KARTE_EU','VISUM_D','AUFENTHALTSGESTATTUNG','DULDUNG','UNGEKLAERT','KEIN_STATUS','UNBEKANNT'
                                                         ]::text[])),
                                                     CONSTRAINT bezugspersonen_coda_status_check CHECK (coda_status::text = ANY (ARRAY['NEIN','JA','UNBEKANNT']::text[])),
                                                     CONSTRAINT bezugspersonen_dolmetsch_bedarf_check CHECK (dolmetsch_bedarf::text = ANY (ARRAY['KEIN','SPRACHDOLMETSCHEN','GEBAERDENSPRACHDOLMETSCHEN','SCHRIFTDOLMETSCHEN','UNGEKLAERT']::text[])),
                                                     CONSTRAINT bezugspersonen_hoer_status_check CHECK (hoer_status::text = ANY (ARRAY['UNBEKANNT','HOEREND','SCHWERHOERIG','GEHOERLOS']::text[])),
                                                     CONSTRAINT bezugspersonen_staatsangehoerigkeit_gruppe_check CHECK (staatsangehoerigkeit_gruppe::text = ANY (ARRAY['DE','EU_EWR','SCHWEIZ','DRITTSTAAT','UNBEKANNT']::text[])),
                                                     CONSTRAINT bezugspersonen_staatsangehoerigkeit_sonderfall_check CHECK (staatsangehoerigkeit_sonderfall::text = ANY (ARRAY['KEINER','UNGEKLAERT','UNBEKANNT','STAATENLOS']::text[]))
);

CREATE TABLE IF NOT EXISTS public.kinder (
                                             braucht_dolmetsch boolean,
                                             geburtsdatum date,
                                             staatsangehoerigkeit_iso2 varchar(2),
                                             id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                             bevorzugte_sprache_code varchar(15),
                                             dolmetsch_sprache_code varchar(15),
                                             muttersprache_code varchar(15),
                                             gebaerdensprache_code varchar(20),
                                             aufenthaltstitel_details varchar(200),
                                             kommunikations_hinweise varchar(500),
                                             aufenthaltstitel_typ varchar(255),
                                             coda_status varchar(255) NOT NULL,
                                             dolmetsch_bedarf varchar(255) NOT NULL,
                                             hauptsprache varchar(255),
                                             hausnummer varchar(255),
                                             hoer_status varchar(255) NOT NULL,
                                             kontakt_email varchar(255),
                                             nachname varchar(255),
                                             ort varchar(255),
                                             plz varchar(255),
                                             staatsangehoerigkeit_gruppe varchar(255) NOT NULL,
                                             staatsangehoerigkeit_sonderfall varchar(255) NOT NULL,
                                             strasse varchar(255),
                                             telefon varchar(255),
                                             vorname varchar(255),

                                             CONSTRAINT kinder_aufenthaltstitel_typ_check CHECK (aufenthaltstitel_typ::text = ANY (ARRAY[
                                                 'DEUTSCH','EU_EWR_FREIZUEGIGKEIT','SCHWEIZ_FREIZUEGIGKEIT','AUFENTHALTSERLAUBNIS','NIEDERLASSUNGSERLAUBNIS',
                                                 'DAUERAUFENTHALT_EU','BLAUE_KARTE_EU','VISUM_D','AUFENTHALTSGESTATTUNG','DULDUNG','UNGEKLAERT','KEIN_STATUS','UNBEKANNT'
                                                 ]::text[])),
                                             CONSTRAINT kinder_coda_status_check CHECK (coda_status::text = ANY (ARRAY['NEIN','JA','UNBEKANNT']::text[])),
                                             CONSTRAINT kinder_dolmetsch_bedarf_check CHECK (dolmetsch_bedarf::text = ANY (ARRAY['KEIN','SPRACHDOLMETSCHEN','GEBAERDENSPRACHDOLMETSCHEN','SCHRIFTDOLMETSCHEN','UNGEKLAERT']::text[])),
                                             CONSTRAINT kinder_hoer_status_check CHECK (hoer_status::text = ANY (ARRAY['UNBEKANNT','HOEREND','SCHWERHOERIG','GEHOERLOS']::text[])),
                                             CONSTRAINT kinder_staatsangehoerigkeit_gruppe_check CHECK (staatsangehoerigkeit_gruppe::text = ANY (ARRAY['DE','EU_EWR','SCHWEIZ','DRITTSTAAT','UNBEKANNT']::text[])),
                                             CONSTRAINT kinder_staatsangehoerigkeit_sonderfall_check CHECK (staatsangehoerigkeit_sonderfall::text = ANY (ARRAY['KEINER','UNGEKLAERT','UNBEKANNT','STAATENLOS']::text[]))
);

CREATE TABLE IF NOT EXISTS public.users (
                                            enabled boolean NOT NULL DEFAULT true,
                                            staatsangehoerigkeit_iso2 varchar(2),
                                            id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                            last_login timestamp(6),
                                            bevorzugte_sprache_code varchar(15),
                                            dolmetsch_sprache_code varchar(15),
                                            muttersprache_code varchar(15),
                                            gebaerdensprache_code varchar(20),
                                            aufenthaltstitel_details varchar(200),
                                            kommunikations_hinweise varchar(500),
                                            aufenthaltstitel_typ varchar(255),
                                            coda_status varchar(255) NOT NULL,
                                            dolmetsch_bedarf varchar(255) NOT NULL,
                                            email varchar(255) NOT NULL UNIQUE,
                                            hausnummer varchar(255),
                                            hoer_status varchar(255) NOT NULL,
                                            kontakt_email varchar(255),
                                            nachname varchar(255),
                                            ort varchar(255),
                                            password_hash varchar(255) NOT NULL,
                                            plz varchar(255),
                                            role varchar(255) NOT NULL,
                                            staatsangehoerigkeit_gruppe varchar(255) NOT NULL,
                                            staatsangehoerigkeit_sonderfall varchar(255) NOT NULL,
                                            strasse varchar(255),
                                            telefon varchar(255),
                                            vorname varchar(255),

                                            facility_id BIGINT,

                                            CONSTRAINT users_aufenthaltstitel_typ_check CHECK (aufenthaltstitel_typ::text = ANY (ARRAY[
                                                'DEUTSCH','EU_EWR_FREIZUEGIGKEIT','SCHWEIZ_FREIZUEGIGKEIT','AUFENTHALTSERLAUBNIS','NIEDERLASSUNGSERLAUBNIS',
                                                'DAUERAUFENTHALT_EU','BLAUE_KARTE_EU','VISUM_D','AUFENTHALTSGESTATTUNG','DULDUNG','UNGEKLAERT','KEIN_STATUS','UNBEKANNT'
                                                ]::text[])),
                                            CONSTRAINT users_coda_status_check CHECK (coda_status::text = ANY (ARRAY['NEIN','JA','UNBEKANNT']::text[])),
                                            CONSTRAINT users_dolmetsch_bedarf_check CHECK (dolmetsch_bedarf::text = ANY (ARRAY['KEIN','SPRACHDOLMETSCHEN','GEBAERDENSPRACHDOLMETSCHEN','SCHRIFTDOLMETSCHEN','UNGEKLAERT']::text[])),
                                            CONSTRAINT users_hoer_status_check CHECK (hoer_status::text = ANY (ARRAY['UNBEKANNT','HOEREND','SCHWERHOERIG','GEHOERLOS']::text[])),
                                            CONSTRAINT users_role_check CHECK (role::text = ANY (ARRAY['ADMIN','FACHKRAFT','TEAMLEITUNG','IEFK','READ_ONLY','DATENSCHUTZBEAUFTRAGTER']::text[])),
                                            CONSTRAINT users_staatsangehoerigkeit_gruppe_check CHECK (staatsangehoerigkeit_gruppe::text = ANY (ARRAY['DE','EU_EWR','SCHWEIZ','DRITTSTAAT','UNBEKANNT']::text[])),
                                            CONSTRAINT users_staatsangehoerigkeit_sonderfall_check CHECK (staatsangehoerigkeit_sonderfall::text = ANY (ARRAY['KEINER','UNGEKLAERT','UNBEKANNT','STAATENLOS']::text[])),
                                            CONSTRAINT fk_users_facility FOREIGN KEY (facility_id) REFERENCES public.facilities(id)
);

-- User <-> Teams (Many-to-Many)
CREATE TABLE IF NOT EXISTS public.user_teams (
                                                 user_id BIGINT NOT NULL,
                                                 team_id BIGINT NOT NULL,
                                                 created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
                                                 CONSTRAINT fk_user_teams_user FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE,
                                                 CONSTRAINT fk_user_teams_team FOREIGN KEY (team_id) REFERENCES public.teams(id) ON DELETE CASCADE,
                                                 CONSTRAINT uk_user_team UNIQUE (user_id, team_id)
);

CREATE INDEX IF NOT EXISTS idx_teams_facility ON public.teams(facility_id);
CREATE INDEX IF NOT EXISTS idx_user_teams_user ON public.user_teams(user_id);
CREATE INDEX IF NOT EXISTS idx_user_teams_team ON public.user_teams(team_id);

-- =========================
-- Kinderschutz & Co (wie bei dir)
-- =========================

CREATE TABLE IF NOT EXISTS public.kinderschutz_faelle (
                                                          gericht_eingeschaltet boolean,
                                                          iefk_pflichtig boolean,
                                                          inobhutnahme_erfolgt boolean,
                                                          created_at timestamp(6),
                                                          id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                                          kind_id bigint NOT NULL,
                                                          teamleitung_id bigint,
                                                          updated_at timestamp(6),
                                                          version bigint,
                                                          zustaendige_fachkraft_id bigint,
                                                          aktenzeichen varchar(255),
                                                          kurzbeschreibung varchar(255),
                                                          letzte_einschaetzung varchar(255),
                                                          status varchar(255),

                                                          CONSTRAINT kinderschutz_faelle_aktenzeichen_key UNIQUE (aktenzeichen),
                                                          CONSTRAINT kinderschutz_faelle_letzte_einschaetzung_check CHECK (letzte_einschaetzung::text = ANY (ARRAY[
                                                              'KEINE_GEFaeHRDUNG','UNKLAR_WEITERE_ABKLAERUNG','LATENTE_GEFaeHRDUNG','AKUTE_GEFaeHRDUNG','INOBHUTNAHME_ERFORDERLICH'
                                                              ]::text[])),
                                                          CONSTRAINT kinderschutz_faelle_status_check CHECK (status::text = ANY (ARRAY[
                                                              'ENTWURF','IN_PRUEFUNG','AKUT','HILFEPLANUNG','ABGESCHLOSSEN','ARCHIVIERT'
                                                              ]::text[])),

                                                          CONSTRAINT fk_kinderschutz_kind FOREIGN KEY (kind_id) REFERENCES public.kinder(id),
                                                          CONSTRAINT fk_kinderschutz_teamleitung FOREIGN KEY (teamleitung_id) REFERENCES public.users(id),
                                                          CONSTRAINT fk_kinderschutz_fachkraft FOREIGN KEY (zustaendige_fachkraft_id) REFERENCES public.users(id)
);

CREATE TABLE IF NOT EXISTS public.fall_gefaehrdungsbereiche (
                                                                fall_id bigint NOT NULL,
                                                                bereich varchar(255),
                                                                CONSTRAINT fall_gefaehrdungsbereiche_bereich_check CHECK (bereich::text = ANY (ARRAY[
                                                                    'VERNACHLAESSIGUNG','KOERPERLICHE_GEWALT','SEELISCHE_MISSBRAUCH','SEXUELLE_GEWALT',
                                                                    'HAUSLICHE_GEWALT_MITBETROFFEN','SUBSTANZKONSUM_IM_HAUSHALT','SONSTIGES','UNKLAR'
                                                                    ]::text[])),
                                                                CONSTRAINT fk_fgb_fall FOREIGN KEY (fall_id) REFERENCES public.kinderschutz_faelle(id)
);

CREATE TABLE IF NOT EXISTS public.gefaehrdung_einschaetzungen (
                                                                  datum date,
                                                                  eltern_beteiligt boolean,
                                                                  iefk_einbezogen boolean,
                                                                  kind_beteiligt boolean,
                                                                  fall_id bigint NOT NULL,
                                                                  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                                                  begruendung_keine_beteiligung varchar(255),
                                                                  ergebnis varchar(255),
                                                                  iefk_ergebnis_kurz varchar(255),
                                                                  iefk_person varchar(255),
                                                                  begruendung oid,
                                                                  CONSTRAINT gefaehrdung_einschaetzungen_ergebnis_check CHECK (ergebnis::text = ANY (ARRAY[
                                                                      'KEINE_GEFaeHRDUNG','UNKLAR_WEITERE_ABKLAERUNG','LATENTE_GEFaeHRDUNG','AKUTE_GEFaeHRDUNG','INOBHUTNAHME_ERFORDERLICH'
                                                                      ]::text[])),
                                                                  CONSTRAINT fk_ge_fall FOREIGN KEY (fall_id) REFERENCES public.kinderschutz_faelle(id)
);

CREATE TABLE IF NOT EXISTS public.kontakt_ereignisse (
                                                         fall_id bigint NOT NULL,
                                                         id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                                         zeitpunkt timestamp(6),
                                                         art varchar(255),
                                                         beteiligte_kurz varchar(255),
                                                         notiz oid,
                                                         CONSTRAINT kontakt_ereignisse_art_check CHECK (art::text = ANY (ARRAY[
                                                             'GESPRAECH','HAUSBESUCH','TELEFONAT','VIDEOCALL','SCHRIFTLICH','FALLKONFERENZ','SONSTIGES'
                                                             ]::text[])),
                                                         CONSTRAINT fk_kontakt_fall FOREIGN KEY (fall_id) REFERENCES public.kinderschutz_faelle(id)
);

CREATE TABLE IF NOT EXISTS public.massnahmen (
                                                 faellig_am date,
                                                 fall_id bigint NOT NULL,
                                                 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                                 status varchar(255),
                                                 titel varchar(255),
                                                 typ varchar(255),
                                                 verantwortlich varchar(255),
                                                 beschreibung oid,
                                                 CONSTRAINT massnahmen_status_check CHECK (status::text = ANY (ARRAY['OFFEN','IN_ARBEIT','ERLEDIGT','VERWORFEN']::text[])),
                                                 CONSTRAINT massnahmen_typ_check CHECK (typ::text = ANY (ARRAY[
                                                     'SOFORTMASSNAHME','ABKLAERUNG','HILFEPLAN_BEZUG','MELDUNG_AN_GERICHT','INOBHUTNAHME','KOOPERATION_SCHULE_KITA','SONSTIGES'
                                                     ]::text[])),
                                                 CONSTRAINT fk_massnahmen_fall FOREIGN KEY (fall_id) REFERENCES public.kinderschutz_faelle(id)
);

CREATE TABLE IF NOT EXISTS public.meldungen_hinweise (
                                                         eingang_am date,
                                                         fall_id bigint NOT NULL,
                                                         id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                                         kontakt_info varchar(255),
                                                         meldende_stelle varchar(255),
                                                         meldungsweg varchar(255),
                                                         inhalt oid,
                                                         CONSTRAINT meldungen_hinweise_meldungsweg_check CHECK (meldungsweg::text = ANY (ARRAY['TELEFON','EMAIL','PERSOENLICH','SCHRIFTLICH','SONSTIGES']::text[])),
                                                         CONSTRAINT fk_meldungen_fall FOREIGN KEY (fall_id) REFERENCES public.kinderschutz_faelle(id)
);

CREATE TABLE IF NOT EXISTS public.unterbringungen (
                                                      bis date,
                                                      erhoben_am date,
                                                      von date,
                                                      id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                                      kind_id bigint NOT NULL,
                                                      art varchar(255),
                                                      datenquelle varchar(255),
                                                      einrichtung_name varchar(255),
                                                      grund_kurz varchar(255),
                                                      ort varchar(255),
                                                      CONSTRAINT unterbringungen_art_check CHECK (art::text = ANY (ARRAY[
                                                          'BEI_ELTERN','BEI_EINEM_ELTERNTEIL','PFLEGEFAMILIE','HEIM_WOHNGRUPPE','KLINIK','INOBHUTNAHME','UNBEKANNT','SONSTIGE'
                                                          ]::text[])),
                                                      CONSTRAINT unterbringungen_datenquelle_check CHECK (datenquelle::text = ANY (ARRAY[
                                                          'KIND','ELTERN','BEZUGSPERSON','SCHULE_KITA','JUGENDAMT','POLIZEI','ARZT','SONSTIGE'
                                                          ]::text[])),
                                                      CONSTRAINT fk_unter_kinder FOREIGN KEY (kind_id) REFERENCES public.kinder(id)
);

CREATE TABLE IF NOT EXISTS public.gesundheitsmerkmale (
                                                          erhoben_am date,
                                                          gueltig_bis date,
                                                          vertraulich boolean,
                                                          wert_zahl integer,
                                                          id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                                          kind_id bigint NOT NULL,
                                                          datenquelle varchar(255),
                                                          typ varchar(255),
                                                          wert_text varchar(255),
                                                          CONSTRAINT gesundheitsmerkmale_datenquelle_check CHECK (datenquelle::text = ANY (ARRAY[
                                                              'KIND','ELTERN','BEZUGSPERSON','SCHULE_KITA','JUGENDAMT','POLIZEI','ARZT','SONSTIGE'
                                                              ]::text[])),
                                                          CONSTRAINT gesundheitsmerkmale_typ_check CHECK (typ::text = ANY (ARRAY[
                                                              'EINSCHRAENKUNG_VORHANDEN','GDB','MERKZEICHEN','PFLEGEGRAD','THERAPIEBEDARF','ALLERGIE_RISIKO','SONSTIGES'
                                                              ]::text[])),
                                                          CONSTRAINT fk_gesund_kinder FOREIGN KEY (kind_id) REFERENCES public.kinder(id)
);

CREATE TABLE IF NOT EXISTS public.kind_bezugsperson_relation (
                                                                 erhoben_am date,
                                                                 gueltig_bis date,
                                                                 gueltig_von date,
                                                                 lebt_im_haushalt boolean,
                                                                 bezugsperson_id bigint NOT NULL,
                                                                 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                                                 kind_id bigint NOT NULL,
                                                                 beziehungstyp varchar(255),
                                                                 datenquelle varchar(255),
                                                                 rolle_im_alltag varchar(255),
                                                                 sorge_hinweis varchar(255),
                                                                 sorge_status varchar(255),
                                                                 CONSTRAINT kind_bezugsperson_relation_beziehungstyp_check CHECK (beziehungstyp::text = ANY (ARRAY[
                                                                     'MUTTER','VATER','PFLEGEMUTTER','PFLEGEVATER','STIEFMUTTER','STIEFVATER','GROSSMUTTER','GROSSVATER','GESCHWISTER',
                                                                     'VORMUND','ERGAENZUNGSPFLEGER','BETREUER_IN','SONSTIGE'
                                                                     ]::text[])),
                                                                 CONSTRAINT kind_bezugsperson_relation_datenquelle_check CHECK (datenquelle::text = ANY (ARRAY[
                                                                     'KIND','ELTERN','BEZUGSPERSON','SCHULE_KITA','JUGENDAMT','POLIZEI','ARZT','SONSTIGE'
                                                                     ]::text[])),
                                                                 CONSTRAINT kind_bezugsperson_relation_rolle_im_alltag_check CHECK (rolle_im_alltag::text = ANY (ARRAY[
                                                                     'ELTERNTEIL','PFLEGEFAMILIE','BETREUUNG','FAMILIENHILFE','EINRICHTUNG','SONSTIGE'
                                                                     ]::text[])),
                                                                 CONSTRAINT kind_bezugsperson_relation_sorge_status_check CHECK (sorge_status::text = ANY (ARRAY['KEIN','TEIL','VOLL','RUHEND','UNBEKANNT']::text[])),
                                                                 CONSTRAINT fk_kbr_bezug FOREIGN KEY (bezugsperson_id) REFERENCES public.bezugspersonen(id),
                                                                 CONSTRAINT fk_kbr_kind FOREIGN KEY (kind_id) REFERENCES public.kinder(id)
);

-- =========================
-- KWS Schema
-- =========================

CREATE TABLE IF NOT EXISTS public.kws_template (
                                                   active boolean NOT NULL,
                                                   max_age_months integer,
                                                   min_age_months integer,
                                                   created_at timestamptz NOT NULL DEFAULT now(),
                                                   id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                                   code varchar(50) NOT NULL UNIQUE,
                                                   audience varchar(255) NOT NULL,
                                                   title varchar(255) NOT NULL,
                                                   version varchar(255) NOT NULL,
                                                   CONSTRAINT kws_template_audience_check CHECK (audience::text = ANY (ARRAY['ALL','YOUTH_OFFICE_ONLY']::text[]))
);

CREATE TABLE IF NOT EXISTS public.kws_template_section (
                                                           sort integer NOT NULL,
                                                           id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                                           template_id bigint NOT NULL,
                                                           section_key varchar(40) NOT NULL,
                                                           title varchar(255) NOT NULL,
                                                           CONSTRAINT fk_kws_section_template FOREIGN KEY (template_id) REFERENCES public.kws_template(id)
);

CREATE TABLE IF NOT EXISTS public.kws_template_item (
                                                        sort integer NOT NULL,
                                                        id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                                        section_id bigint NOT NULL,
                                                        answer_type varchar(20) NOT NULL,
                                                        item_key varchar(40) NOT NULL,
                                                        label text NOT NULL,
                                                        CONSTRAINT kws_template_item_answer_type_check CHECK (answer_type::text = ANY (ARRAY['TRI_STATE','TEXT','DATE']::text[])),
                                                        CONSTRAINT fk_kws_item_section FOREIGN KEY (section_id) REFERENCES public.kws_template_section(id)
);

CREATE TABLE IF NOT EXISTS public.kws_run (
                                              assessment_date date NOT NULL,
                                              next_review_date date,
                                              created_at timestamptz NOT NULL DEFAULT now(),
                                              created_by_user_id bigint NOT NULL,
                                              finalized_at timestamptz,
                                              id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                              kind_id bigint NOT NULL,
                                              parent_run_id bigint,
                                              related_run_id bigint,
                                              template_id bigint NOT NULL,
                                              status varchar(10) NOT NULL,
                                              reason text,
                                              CONSTRAINT kws_run_status_check CHECK (status::text = ANY (ARRAY['DRAFT','FINAL']::text[])),
                                              CONSTRAINT fk_kws_run_kind FOREIGN KEY (kind_id) REFERENCES public.kinder(id),
                                              CONSTRAINT fk_kws_run_parent FOREIGN KEY (parent_run_id) REFERENCES public.kws_run(id),
                                              CONSTRAINT fk_kws_run_related FOREIGN KEY (related_run_id) REFERENCES public.kws_run(id),
                                              CONSTRAINT fk_kws_run_template FOREIGN KEY (template_id) REFERENCES public.kws_template(id),
                                              CONSTRAINT kws_run_created_by_fk FOREIGN KEY (created_by_user_id) REFERENCES public.users(id)
);

CREATE TABLE IF NOT EXISTS public.kws_answer (
                                                 date_value date,
                                                 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                                 item_id bigint NOT NULL,
                                                 run_id bigint NOT NULL,
                                                 updated_at timestamptz NOT NULL DEFAULT now(),
                                                 comment text,
                                                 text_value text,
                                                 tri_state varchar(255),
                                                 CONSTRAINT kws_answer_tri_state_check CHECK (tri_state::text = ANY (ARRAY['JA','NEIN','KEINE_ANGABE']::text[])),
                                                 CONSTRAINT fk_kws_answer_item FOREIGN KEY (item_id) REFERENCES public.kws_template_item(id),
                                                 CONSTRAINT fk_kws_answer_run FOREIGN KEY (run_id) REFERENCES public.kws_run(id)
);

CREATE TABLE IF NOT EXISTS public.kws_run_event (
                                                    created_at timestamptz NOT NULL DEFAULT now(),
                                                    created_by_user_id bigint NOT NULL,
                                                    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                                    run_id bigint NOT NULL,
                                                    type varchar(20) NOT NULL,
                                                    payload jsonb,
                                                    CONSTRAINT fk_kws_event_run FOREIGN KEY (run_id) REFERENCES public.kws_run(id),
                                                    CONSTRAINT kws_run_event_created_by_fk FOREIGN KEY (created_by_user_id) REFERENCES public.users(id)
);