package org.thomcgn.backend.cases.model;

public enum Beziehungstyp {
    MUTTER, VATER,
    PFLEGEMUTTER, PFLEGEVATER,
    STIEFMUTTER, STIEFVATER,
    GROSSMUTTER, GROSSVATER,
    GESCHWISTER,
    VORMUND, ERGAENZUNGSPFLEGER,
    BETREUER_IN, SONSTIGE
}
