package org.thomcgn.backend.cases.model;

public enum Gefaehrdungsbereich {
    VERNACHLAESSIGUNG,
    KOERPERLICHE_GEWALT,
    SEELISCHE_MISSBRAUCH,
    SEXUELLE_GEWALT,
    HAUSLICHE_GEWALT_MITBETROFFEN,
    SUBSTANZKONSUM_IM_HAUSHALT,
    SONSTIGES,
    UNKLAR
}
