spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true
spring.flyway.baseline-version=0
spring.flyway.baseline-description=baseline

spring.jpa.hibernate.ddl-auto=validate

spring.autoconfigure.exclude=org.springframework.boot.security.autoconfigure.UserDetailsServiceAutoConfiguration

# JWT Secret (in Prod besser über ENV überschreiben)
security.jwt.secret=dev-dev-dev-dev-dev-dev-dev-dev-dev-dev-dev-dev

# Cookies
kidoc.cookies.secure=true

# Server
server.port=8080
server.ssl.enabled=false

# GitHub Integration
github.token=${GITHUB_TOKEN}
github.owner=thomcgn
github.repo=nvg8
github.webhook-secret=${GITHUB_WEBHOOK_SECRET}