spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=postgres

# HTTPS lokal (für Secure Cookies)
server.ssl.enabled=true
server.ssl.key-store=classpath:local-keystore.p12
server.ssl.key-store-password=changeit
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=local

# Debug Logging
logging.level.org.springframework.jdbc=DEBUG
logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.hibernate.orm.jdbc.bind=TRACE
logging.level.org.springframework.dao=DEBUG

logging.level.org.springframework.web=DEBUG
#logging.level.org.springframework.web.servlet.mvc.method.annotation=DEBUG
#logging.level.org.springframework.web.servlet.DispatcherServlet=DEBUG
#logging.level.org.springframework.security=TRACE
logging.level.org.springframework.web.servlet.DispatcherServlet=DEBUG
logging.level.org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping=DEBUG
logging.level.org.springframework.http.converter.json=DEBUG
logging.level.org.springframework.security=DEBUG